general:
  dtc:
    messagingType: zmq
    timeout: 10
    nodesNumber: 5

  criptoki:
    manufacturerId: "NICLabs"
    model: "TCHSM"
    description: "Implementación de PKCS11"
    versionMajor: 2
    versionMinor: 40
    serialnumber: "1"
    minPinLen: 3
    maxPinLen: 10
    maxSessionCount: 5
    databaseType: sqlite3
    slots:
      - label: slot1

sqlite3:
  path: db.sqlite3

zmq:
  publicKey: "changeme"
  privateKey: "changeme"
      ip: 0.0.0.0
  port: 2031
  nodes:
    - ip: 127.0.0.1
      publicKey: "changeme"
      port: 9871
    - ip: 127.0.0.1
      publicKey: "changeme"
      port: 9873
    - ip: 127.0.0.1
      publicKey: "changeme"
      port: 9875
    - ip: 127.0.0.1
      publicKey: "changeme"
      port: 9877
    - ip: 127.0.0.1
      publicKey: "changeme"
      port: 9879
