dtc:
  messaging_type: zmq
  instance_id: "libdtc"
  timeout: 10
  nodes_number: 5
  threshold: 3

criptoki:
  manufacturer_id: "NICLabs"
  model: "TCHSM"
  description: "Implementación de PKCS11"
  version_major: 2
  version_minor: 40
  serialnumber: "1"
  min_pin_len: 3
  max_pin_len: 10
  max_session_count: 5
  database_type: sqlite3
  slots:
    - label: slot1

sqlite3:
  path: db.sqlite3

zmq:
  public_key: "changeme"
  private_key: "changeme"
      ip: 0.0.0.0
  port: 2031
  nodes:
    - ip: 127.0.0.1
      public_key: "changeme"
      port: 9871
    - ip: 127.0.0.1
      public_key: "changeme"
      port: 9872
    - ip: 127.0.0.1
      public_key: "changeme"
      port: 9873
    - ip: 127.0.0.1
      public_key: "changeme"
      port: 9874
    - ip: 127.0.0.1
      public_key: "changeme"
      port: 9875
