dtc:
  messaging_type: zmq
  instance_id: libdtc

criptoki:
  database_type: sqlite3
  nodes_number: 10
  threshold: 8
  slots:
    - label: slot1

sqlite3:
  path: db.sqlite3

zmq:
  timeout: 10
  public_key: PubK
  private_key: PrivK
  network:
    ip: 1.2.3.4
    port: 2031
  nodes:
    - network:
        ip: 1.2.3.4
        port: 2030
      public_key: PubK
    - network:
        ip: 1.2.3.4
        port: 2031
      public_key: PubK