dtc:
  messaging_type: zmq
  instance_id: libdtc
  timeout: 10

criptoki:
  database_type: sqlite3
  nodes_number: 10
  threshold: 8
  slots:
             - label: slot1

sqlite3:
  path: db.sqlite3

zmq:
  public_key: PubK
  private_key: PrivK
  ip: 1.2.3.4
  router_port: 2031 # Router port
  push_port: 2031 # Router port
  nodes:
    - network:
      ip: 1.2.3.4
      public_key: PubK
    - network:
      ip: 1.2.3.4
      public_key: PubK