dtc:
  messaging_type: zmq
  instance_id: libdtc
  timeout: 10
  nodes_number: 10
  threshold: 8

criptoki:
  manufacturer_id: "NICLabs"
  model: "TCHSM"
  version_major: 2
  version_minor: 0
  min_pin_len: 3
  max_pin_len: 10
  max_session_count: 5
  database_type: sqlite3
  slots:
    - label: slot1

sqlite3:
  path: db.sqlite3

zmq:
  public_key: PubK
  private_key: PrivK
  ip: 1.2.3.4
  router_port: 2031 # Router port
  push_port: 3031 # Router port
  nodes:
    - ip: 1.2.3.4
      public_key: PubK
    - ip: 1.2.3.4
      public_key: PubK
