dtc:
  public_key: PubK
  private_key: PrivK
  instance_id: libdtc
  nodes:
    - ip: 1.2.3.4
      public_key: PubK
      sub_port: 2030
      dealer_port: 2031

criptoki:
  database_path: db.sqlite3
  nodes_number: 10
  threshold: 8
  slots:
    - label: slot1
  timeout: 10
