config:
  publickey: '{ru14[eTvFFr^o}wL}#J[z4{ci7+P1gHv<on#[{z'
  privatekey: lrM1EuIV}%[?jhiYI(MxqgLrg=ws5=)!y!G8Xih!
  host: 0.0.0.0
  port: 2030
  server:
    publickey: '{0j3IXL0Jw:)K$b1@(1=<8z/joPM.c+EXVBMS>7$'
    host: 172.18.0.1
    port: 3030
    keys: []
