config:
  publickey: '@?Bpu79j8JG1$BGhUHx@bl?jaLB6Tg].V3XjCHiy'
  privatekey: jlACUxB<j((FW(^bISdBX[[&q?BldP4n4aJT&T4#
  host: 0.0.0.0
  port: 2030
  server:
    publickey: '{0j3IXL0Jw:)K$b1@(1=<8z/joPM.c+EXVBMS>7$'
    host: 172.18.0.1
    port: 3030
    keys: []
