general:
  # logfile undefined: the logs are going to be outputted in stdout/stderr
# logfile: /tmp/dtc.log
  dtc:
    messagingType: zmq
    nodesNumber: 5
    threshold: 3

  criptoki:
    manufacturerId: "NICLabs"
    model: "TCHSM"
    description: "Implementación de PKCS11"
    serialnumber: "1"
    minPinLen: 3
    maxPinLen: 10
    maxSessionCount: 5
    databaseType: sqlite3
    slots:
      - label: TCBHSM

sqlite3:
  path: ./db.sqlite3

zmq:
  timeout: 10
  publicKey: "{0j3IXL0Jw:)K$b1@(1=<8z/joPM.c+EXVBMS>7$"
  privateKey: "F(/uq@m$}KW>)X=0yKRh}lg!N![Efl<@3<Bbelp3"
  host: dtc
  port: 3030
  nodes:
    - host: node1
      publicKey: '@?Bpu79j8JG1$BGhUHx@bl?jaLB6Tg].V3XjCHiy'
      port: 2030
    - host: node2
      publicKey:  '{ru14[eTvFFr^o}wL}#J[z4{ci7+P1gHv<on#[{z'
      port: 2030
    - host: node3
      publicKey: '*@tRX8)p=ty]7oZbJZ/Stm>=3Qd{P$[IG?ba>q3f'
      port: 2030
    - host: node4
      publicKey: pZd<H6rhZ:3Eky<5A=Gvq]BLHL^a-@H+)tP?L-+7
      port: 2030
    - host: node5
      publicKey: WEz4<>x8dul]2ELx$r60C-gTVf0O8=M>Z7ZV%ihW
      port: 2030
